data_cfg:
  dataset_name: CCPG
  # TODO
  dataset_root: /data/CCPG/Released/CCPG-ratio-pkl/
  dataset_partition: ./opengait/datasets/CCPG/CCPG.json
  data_in_use: [True, True] # images / real_ratios
  num_workers: 1
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: CCPG

# data_cfg:
#   dataset_name: CASIA-B
#   dataset_root: /data4/casiab-128-end2end/
#   dataset_partition: ./opengait/datasets/CASIA-B/CASIA-B.json
#   data_in_use: [False, True, True, False]
#   num_workers: 1
#   remove_no_gallery: false # Remove probe if no gallery for it
#   test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: True
  restore_hint: 40000
  save_name: BigGait__Dinov2_Gaitbase_Frame30
  eval_func: evaluate_CCPG
  sampler:
    batch_shuffle: false
    batch_size: 1 # GPUs number
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 250 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  sils_transform: 0
  transform:
    - type: BaseRgbTransform
      cutting: 0
    - type: NoOperation
    # - type: NoOperation
    # - type: BaseRgbTransform
    #   cutting: 0

model_cfg:
  model: BigGait__Dinov2_Gaitbase
  pretrained_dinov2: ./pretrained_LVMs/dinov2_vits14_pretrain.pth                   # DINOv2 Download Link: https://dl.fbaipublicfiles.com/dinov2/dinov2_vits14/dinov2_vits14_pretrain.pth
  pretrained_mask_branch: ./pretrained_LVMs/MaskBranch_vits14.pt                # pretrained_mask_branch: None or MaskBranch Download Link: https://drive.google.com/drive/folders/1zrWPUsrbCpwxoLgfom3d2irgxkBqtXqc?usp=sharing
  pretrained_biggait: ./pretrained_LVMs/BigGait__Dinov2_Gaitbase.pt
  image_size: 224                                                               # 448x224
  sils_size: 32                                                                 # 64x32

  Denoising_Branch:
    source_dim: 1536
    target_dim: 16
    p: 0
    softmax: True
    Relu: True
    Up: False

  Appearance_Branch:
    source_dim: 1536
    target_dim: 16
    p: 0
    softmax: False
    Relu: False
    Up: False

  Mask_Branch:
    source_dim: 384
    target_dim: 2
    p: 0.5
    softmax: True
    Relu: False
    Up: True

  AttentionFusion:
    in_channels: 64
    squeeze_ratio: 16
    feat_len: 2

  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    in_channel: 1
    channels: # Layers configuration for automatically model construction
      - 64
      - 128
      - 256
      - 512
    layers:
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    # class_num: 100
    class_num: 571
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16